import { Properties } from '@/types'

// realEstateDataset.json
export const properties: Properties[] = [
  {
    propertyId: 1,
    name: 'Apartment for sale at Alphanam Luxury Apartment Danang',
    featuredId: 'sale',
    categoryId: 'house',
    districtId: '1',
    location: '123 Main Street',
    price: 1500000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 500,
    areaOfUse: 300,
    numberOfBedroom: 5,
    numberOfToilet: 4,
    direction: 'Northwest',
    numberOfFloor: 2,
    createdAt: '2023-01-01T12:00:00Z',
    updatedAt: '2023-01-05T14:30:00Z',
    description: 'A stunning luxury villa with beautiful views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 2,
    name: 'Indochina Riverside Danang apartment for sale',
    featuredId: 'sale',
    categoryId: 'apartment',
    districtId: '2',
    location: '456 Oak Avenue',
    price: 800000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 200,
    areaOfUse: 120,
    numberOfBedroom: 2,
    numberOfToilet: 2,
    direction: 'South',
    numberOfFloor: 1,
    createdAt: '2023-02-01T10:00:00Z',
    updatedAt: '2023-02-05T12:45:00Z',
    description: 'A modern apartment in a convenient location.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-luxury-da-nang.jpg',
  },
  {
    propertyId: 3,
    name: 'Apartment for sale at Alphanam Luxury Apartment Danang',
    featuredId: 'sale',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  
  {
    propertyId: 4,
    name: 'Apartment for sale at Alphanam Luxury Apartment Danang ',
    featuredId: 'rent',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 5,
    name: 'Indochina Riverside Danang apartment for sale',
    featuredId: 'rent',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-luxury-da-nang.jpg',
  },
  {
    propertyId: 6,
    name: 'Beachfront House',
    featuredId: 'rent',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'sale',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'sale',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'sale',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'rent',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'rent',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'rent',
    categoryId: 'house',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  // Add more real estate objects as needed
]
