import { Properties } from '@/types'

// realEstateDataset.json
export const properties: Properties[] = [
  {
    propertyId: 1,
    name: 'Apartment for sale at Alphanam Luxury Apartment amfkldafanfjdsanfksanfkjdnfjasnfkjdsnjkasnfkdsnjk',
    featuredId: 'sale',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '1',
    location: '123 Main Street',
    price: 1500000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 500,
    areaOfUse: 300,
    numberOfBedroom: 5,
    numberOfToilet: 4,
    direction: 'Northwest',
    numberOfFloor: 2,
    createdAt: '2023-01-01T12:00:00Z',
    updatedAt: '2023-01-05T14:30:00Z',
    description: 'A stunning luxury villa with beautiful views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 2,
    name: 'Indochina Riverside Danang apartment for sale',
    featuredId: 'sale',
    categoryId: 'apartment',
    code: 'VN23323',
    districtId: '2',
    location: '456 Oak Avenue',
    price: 800000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 200,
    areaOfUse: 120,
    numberOfBedroom: 2,
    numberOfToilet: 2,
    direction: 'South',
    numberOfFloor: 1,
    createdAt: '2023-02-01T10:00:00Z',
    updatedAt: '2023-02-05T12:45:00Z',
    description: `
    Resale Apartment Da Nang in Fusion Suites, Son Tra District, walk to My Khe Beach
    This residence flat provides entirely comfortable feeling of its interiors and architects
    Fully-furnished, 2-bedrooms, 2-bathroom, balcony, kitchen area, laundry, over 62sqm
    RESALE APARTMENT DA NANG
    Apartments located in the vicinity of essential destination, right at the white sandy beach, 10 minutes from the airport, tasteful seafood restaurants are in few steps from your door;
    Decoration are harmonious, designing in an open way, sense of airy make you feel at home
    Internal amenities are superb, besides from spectacular view towards the sea of the area, it offers free infinite swimming pool, fitness center as well as bring you closer to natural with plenty of trees
    Fusion Suites and Villa is one of the most luxury, promising and interesting beachfront project that attracts investors, suitable for living, will not let you down,
    Available for Sale: 3.2 billion VND
    
    Viet Nam ownership permanent, can handover to expats
    
    Schedule visiting or further details Feel free to give a call or direct messgage to me, let me know your request and we will guide you home.
    
    Find us on Facebook
    
    Contact number 0917 112 855 (WhatsApp-Zalo-Kaotalk-Viber-Wechat)`,
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-luxury-da-nang.jpg',
  },
  {
    propertyId: 3,
    name: 'Apartment for sale at Alphanam Luxury Apartment Danang',
    featuredId: 'sale',
    categoryId: 'house',
    code: 'VN32323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },

  {
    propertyId: 4,
    name: 'Apartment for sale at Alphanam Luxury Apartment Danang ',
    featuredId: 'rent',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 5,
    name: 'Indochina Riverside Danang apartment for sale',
    featuredId: 'rent',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-luxury-da-nang.jpg',
  },
  {
    propertyId: 6,
    name: 'Beachfront House',
    featuredId: 'rent',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'sale',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'sale',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'sale',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'rent',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'rent',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  {
    propertyId: 7,
    name: 'Beachfront House',
    featuredId: 'rent',
    categoryId: 'house',
    code: 'VN23323',
    districtId: '3',
    location: '789 Beach Road',
    price: 2200000,
    currencyCode: 'USD',
    status: 'available',
    landArea: 600,
    areaOfUse: 400,
    numberOfBedroom: 6,
    numberOfToilet: 5,
    direction: 'West',
    numberOfFloor: 3,
    createdAt: '2023-03-01T14:00:00Z',
    updatedAt: '2023-03-10T16:20:00Z',
    description: 'A spacious beachfront house with panoramic ocean views.',
    images:
      'https://toanhuyhoang.com/wp-content/uploads/2023/03/ban-can-ho-tai-alphanam-luxury-apartment.jpg',
  },
  // Add more real estate objects as needed
]
